"""Generate direwolf.conf from the RNM unified config."""

from __future__ import annotations

from rnm.config.schema import DirewolfInterface


def generate_direwolf_conf(iface_name: str, iface: DirewolfInterface) -> str:
    """Generate direwolf.conf content from our config.

    Reference: https://github.com/wb2osz/direwolf/tree/master/doc
    Key directives used:
      ADEVICE - audio device (ALSA plughw name)
      CHANNEL - select channel (0-7)
      MYCALL  - station callsign with SSID
      MODEM   - 1200 (AFSK) or 9600 (GFSK/K9NG)
      PTT     - push-to-talk control method
      TXDELAY/TXTAIL/SLOTTIME/PERSIST - timing parameters
      KISSPORT - KISS TCP server port for Reticulum
      AGWPORT  - AGW protocol port (disabled, not needed)
    """
    lines = [
        "# Auto-generated by reticulum-node-manager",
        f"# Interface: {iface_name}",
        "",
        "# ---- Audio device ----",
        f"ADEVICE {iface.audio_device}",
        "",
        "# ---- Channel configuration ----",
        f"CHANNEL {iface.channel}",
        f"MYCALL {iface.callsign}",
        f"MODEM {iface.modem}",
        "",
    ]

    # PTT configuration
    if iface.ptt.type == "serial" and iface.ptt.device:
        lines.append(f"PTT {iface.ptt.device} {iface.ptt.line}")
    elif iface.ptt.type == "gpio" and iface.ptt.gpio_pin is not None:
        lines.append(f"PTT GPIO {iface.ptt.gpio_pin}")
    elif iface.ptt.type == "cm108":
        lines.append("PTT CM108")

    # Timing parameters
    lines.extend([
        "",
        "# ---- Timing ----",
        f"TXDELAY {iface.timing.txdelay}",
        f"TXTAIL {iface.timing.txtail}",
        f"SLOTTIME {iface.timing.slottime}",
        f"PERSIST {iface.timing.persist}",
    ])

    # KISS TCP server for Reticulum to connect to
    lines.extend([
        "",
        "# ---- KISS TCP interface for Reticulum ----",
        f"KISSPORT {iface.kiss_port}",
    ])

    # Disable AGW port (not needed for our use case)
    lines.append("AGWPORT 0")

    # User-supplied extra config lines
    if iface.extra_config:
        lines.extend(["", "# ---- User extra config ----", iface.extra_config.rstrip()])

    return "\n".join(lines) + "\n"
