"""Generate Reticulum config from the RNM unified config."""

from __future__ import annotations

from rnm.config.schema import RNMConfig


def generate_reticulum_config(config: RNMConfig) -> str:
    """Generate Reticulum config file content.

    Reference: https://reticulum.network/manual/interfaces.html
    Uses TCPClientInterface with kiss_framing = True to connect
    to Direwolf and FreeDV TNC2 KISS TCP servers.

    The generated config is written to a managed directory
    (not ~/.reticulum/) to avoid conflicting with existing setups.
    rnsd is launched with --config pointing to this directory.
    """
    lines = [
        "# Auto-generated by reticulum-node-manager",
        "# Manual edits will be overwritten on next start",
        "",
        "[reticulum]",
        f"  enable_transport = {str(config.reticulum.enable_transport)}",
        f"  share_instance = {str(config.reticulum.share_instance)}",
        f"  shared_instance_port = {config.reticulum.shared_instance_port}",
        f"  instance_control_port = {config.reticulum.instance_control_port}",
        "",
        "[logging]",
        f"  loglevel = {config.reticulum.loglevel}",
        "",
        "[interfaces]",
    ]

    # Generate TCPClientInterface entries for each enabled TNC
    for iface_name, iface in config.interfaces.items():
        if not iface.enabled:
            continue

        rns_name = f"{config.node.name} {iface_name}"
        iface_config = config.reticulum.interface_config.get(iface_name)

        lines.extend([
            "",
            f"  [[{rns_name}]]",
            "    type = TCPClientInterface",
            "    enabled = yes",
            "    kiss_framing = True",
            "    target_host = 127.0.0.1",
            f"    target_port = {iface.kiss_port}",
        ])

        if iface_config:
            if iface_config.announce_rate_target is not None:
                lines.append(f"    announce_rate_target = {iface_config.announce_rate_target}")
            if iface_config.announce_rate_grace is not None:
                lines.append(f"    announce_rate_grace = {iface_config.announce_rate_grace}")
            if iface_config.bandwidth is not None:
                lines.append(f"    bandwidth = {iface_config.bandwidth}")

    # Additional user-defined Reticulum interfaces (TCP server, backbone, etc.)
    for name, params in config.reticulum.additional_interfaces.items():
        lines.extend([
            "",
            f"  [[{name}]]",
        ])
        for key, value in params.items():
            lines.append(f"    {key} = {value}")

    return "\n".join(lines) + "\n"
