"""Generate Reticulum config from the RNM unified config."""

from __future__ import annotations

from rnm.config.schema import RNMConfig, SerialKISSInterface


def generate_reticulum_config(config: RNMConfig) -> str:
    """Generate Reticulum config file content.

    Reference: https://reticulum.network/manual/interfaces.html
    Uses TCPClientInterface with kiss_framing = True to connect
    to Direwolf and FreeDV TNC2 KISS TCP servers.

    The generated config is written to a managed directory
    (not ~/.reticulum/) to avoid conflicting with existing setups.
    rnsd is launched with --config pointing to this directory.
    """
    lines = [
        "# Auto-generated by reticulum-node-manager",
        "# Manual edits will be overwritten on next start",
        "",
        "[reticulum]",
        f"  enable_transport = {str(config.reticulum.enable_transport)}",
        f"  share_instance = {str(config.reticulum.share_instance)}",
        f"  shared_instance_port = {config.reticulum.shared_instance_port}",
        f"  instance_control_port = {config.reticulum.instance_control_port}",
    ]

    if config.reticulum.instance_name:
        lines.append(f"  instance_name = {config.reticulum.instance_name}")

    lines.extend([
        "",
        "[logging]",
        f"  loglevel = {config.reticulum.loglevel}",
        "",
        "[interfaces]",
    ])

    # Generate interface entries for each enabled interface
    for iface_name, iface in config.interfaces.items():
        if not iface.enabled:
            continue

        rns_name = f"{config.node.name} {iface_name}"
        iface_config = config.reticulum.interface_config.get(iface_name)

        if isinstance(iface, SerialKISSInterface):
            # Direct serial KISS — Reticulum's native KISSInterface
            lines.extend([
                "",
                f"  [[{rns_name}]]",
                "    type = KISSInterface",
                "    enabled = yes",
                f"    port = {iface.device}",
                f"    speed = {iface.speed}",
                f"    preamble = {iface.preamble}",
                f"    txtail = {iface.txtail}",
                f"    persistence = {iface.persistence}",
                f"    slottime = {iface.slottime}",
                f"    flow_control = {str(iface.flow_control)}",
            ])
        else:
            # Direwolf / FreeDV TNC2 — connect via TCP KISS
            lines.extend([
                "",
                f"  [[{rns_name}]]",
                "    type = TCPClientInterface",
                "    enabled = yes",
                "    kiss_framing = True",
                "    target_host = 127.0.0.1",
                f"    target_port = {iface.kiss_port}",
            ])

        if iface_config:
            if iface_config.announce_rate_target is not None:
                lines.append(f"    announce_rate_target = {iface_config.announce_rate_target}")
            if iface_config.announce_rate_grace is not None:
                lines.append(f"    announce_rate_grace = {iface_config.announce_rate_grace}")
            if iface_config.bandwidth is not None:
                lines.append(f"    bandwidth = {iface_config.bandwidth}")

    # Additional user-defined Reticulum interfaces (TCP server, backbone, etc.)
    for name, params in config.reticulum.additional_interfaces.items():
        lines.extend([
            "",
            f"  [[{name}]]",
        ])
        for key, value in params.items():
            lines.append(f"    {key} = {value}")

    return "\n".join(lines) + "\n"
