#!/bin/bash
# Generates udev rules to give persistent names to USB audio/serial devices.
# Run with devices plugged in to the ports you intend to use permanently.

set -e

echo "USB Device Pinning — Generating udev rules"
echo "============================================"
echo ""

RULES_FILE="/etc/udev/rules.d/99-rnm-devices.rules"
echo "# Auto-generated by reticulum-node-manager" | sudo tee "$RULES_FILE" > /dev/null

echo "=== USB Audio Devices ==="
echo "Listing connected USB audio devices..."
echo ""

aplay -l 2>/dev/null | grep "^card" | while read -r line; do
    CARD_NUM=$(echo "$line" | grep -oP 'card \K\d+')
    CARD_NAME=$(echo "$line" | grep -oP '\[.*?\]' | head -1 | tr -d '[]')
    DEVICE_PATH=$(readlink -f "/sys/class/sound/card${CARD_NUM}/device" 2>/dev/null || echo "")

    if [ -n "$DEVICE_PATH" ] && [[ "$DEVICE_PATH" == *"usb"* ]]; then
        KERNEL_PATH=$(echo "$DEVICE_PATH" | grep -oP '/usb\d+/[\d\.\-]+/[\d\.\-]+')
        echo "  Card $CARD_NUM: $CARD_NAME"
        echo "    USB path: $KERNEL_PATH"
        echo ""

        read -p "  Assign persistent name for this device (e.g. hf_audio, vhf_audio, or skip): " ALIAS
        if [ -n "$ALIAS" ] && [ "$ALIAS" != "skip" ]; then
            echo "# $CARD_NAME -> $ALIAS" | sudo tee -a "$RULES_FILE" > /dev/null
            echo "SUBSYSTEM==\"sound\", DEVPATH==\"*${KERNEL_PATH}*\", ATTR{id}=\"$ALIAS\"" | sudo tee -a "$RULES_FILE" > /dev/null
        fi
    fi
done

echo ""
echo "=== USB Serial Devices ==="
echo "For serial devices, use /dev/serial/by-id/ paths in your config."
echo "These are already persistent. Available devices:"
ls -la /dev/serial/by-id/ 2>/dev/null || echo "  (no USB serial devices found)"

echo ""
echo "Rules written to: $RULES_FILE"
echo "Reload with: sudo udevadm control --reload-rules && sudo udevadm trigger"
